source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.7'
gem 'cassandra-driver', '~> 3.0.3'
gem 'hdeploy', '~> 0.1.1'
gem 'json', '~> 1.8.3'
gem 'sqlite3', '~> 1.3.13'
gem 'eventmachine', '~> 1.2.5'
gem 'pry'
gem 'bcrypt'

